version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04

    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel-cache

      - run: apt-get update && apt-get -y install pkg-config zip g++ zlib1g-dev unzip python curl
      - run: cd /tmp/ && curl -LO https://github.com/bazelbuild/bazel/releases/download/0.5.4/bazel-0.5.4-installer-linux-x86_64.sh
      - run: bash /tmp/bazel-0.5.4-installer-linux-x86_64.sh
      - run: cd test && bazel test --test_output=errors //...
